version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    #network_mode: "host"
    #docker ps -a
    #internal docker
    volumes:
      - ./backend:/app
      - ./backend/db.sqlite3:/app/db.sqlite3  # Монтируем базу
      #- ./tests/postman_collection.json:/app/postman_collection.json  # Монтируем Postman коллекцию
    depends_on:
      frontend:
        condition: service_started  # frontend не должен блокировать запуск backend


  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app