version: "3.8"

services:
  backend:
    container_name: backend
    build: ./backend
    ports:
      - "8000:8000"
    networks:
      - default
    #network_mode: "host"
    #docker ps -a
    #internal docker
    volumes:
      - ./backend:/app
      - ./backend/db.sqlite3:/app/db.sqlite3  # Монтируем базу
      #- ./tests/postman_collection.json:/app/postman_collection.json  # Монтируем Postman коллекцию
    depends_on:
      frontend:
        condition: service_started  # frontend не должен блокировать запуск backend


  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - "3000:3000"
    networks:
      - default
    volumes:
      - ./frontend:/app

  newman:
    image: postman/newman
    depends_on:
      - backend
    command: run tests/postman_collection.json --env-var base_url="http://backend:8000" --reporters cli,junit

  # newman:
  #   image: postman/newman
  #   depends_on:
  #     - backend
  #   networks:
  #     - default
  #   volumes:
  #     - ./tests:/etc/newman
  #   command: >
  #     run /etc/newman/postman_collection.json 
  #     --env-var base_url="http://backend:8000" 
  #     --reporters cli,junit