version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    network_mode: "host"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://backend:8000/"]
      interval: 5s
      retries: 5
    volumes:
      - ./backend:/app
      - ./backend/db.sqlite3:/app/db.sqlite3  # Монтируем базу
      #- ./tests/postman_collection.json:/app/postman_collection.json  # Монтируем Postman коллекцию
    depends_on:
      - frontend

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app