name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Compose
        run: |
          cd "Lab Work №5/src/backend"
          docker compose up -d  # Запускаем контейнеры в фоне
          sleep 10  # Даем время на запуск бэкенда и базы данных

      - name: Run Django migrations
        run: docker compose exec -T backend python manage.py migrate

      - name: Run Django tests
        run: docker compose exec -T backend python manage.py test

      - name: Install Newman
        run: npm install -g newman

      - name: Run Postman Tests
        run: docker compose exec -T backend newman run /app/tests/postman_collection.json --reporters cli,junit --reporter-junit-export results.xml

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: postman-test-results
          path: results.xml

      - name: Stop and remove Docker containers
        run: docker compose down
